version: '3.1'

services:

  chat-server-app:
    build: ./ChatServerApp
    restart: always
    ports:
      - 8002:8002
    
  chat-server-backend:
    build: ./ChatServerBackend
    restart: always
    ports:
      - 8001:8001
    

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - "dbdata:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
