server:
  port: ${SERVER_PORT:8001}
spring:
  application:
    name: ChatBackend
  datasource:
    url: jdbc:mysql://${DATABASE_URL:db}:${DATABASE_PORT:3306}/${DATABASE_NAME:test}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:example}
  jpa:
    hibernate:
      ddl-auto: update
