server:
  port: 8001
 
spring:
  application:
    name: ChatBackend
  datasource:
    url: jdbc:mysql://db:3306/test
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: update